// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Author    string `json:"author"`
	Published bool   `json:"published"`
}

type Mutation struct {
}

type NewBook struct {
	Title  string `json:"title"`
	Author string `json:"author"`
}

type Query struct {
}
