// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

export interface Exoplanet {
	name: string
	distance_ly: number
	habitability: number
}

export interface ExoplanetQueryRequest {
	max_distance_ly: number // Max distance in light-years
	min_habitability: number // Habitability score (0-1)
}

export interface ExoplanetQueryResponse {
	exoplanets: Array<Exoplanet>
}

